### ISSUE TITLE
Clean build folder in pep517 builds

### ISSUE THREAD

**Issue by mcarans** [ionelmc/tox-wheel#15]
Thanks for this helpful tool. One issue I have run into is that when I delete a source Python file, it still ends up in the wheel because the {project root}/build folder doesn't appear to get cleaned and seems to be used for building the wheel as far as I can tell. Is there any way to force a clean of {project root}/build before building the wheel?

**Comment by mcarans** [comment]
@ionelmc Just wondering when you plan to release a new version with this fix on pypi?

**Comment by ionelmc** [comment]
This week. Ping me if i forget 🤦‍♂️

**Comment by mcarans** [comment]
Hi @ionelmc, just pinging on this

**Comment by ionelmc** [comment]
Released 0.7.0.
