### ISSUE TITLE
wheel_pep517 can trigger allowlist_externals warning

### ISSUE THREAD

**Issue by tucked** [ionelmc/tox-wheel#24]
```
.tox create: /disk1/workspace/CI-someorg-somerepo/somerepo/.tox/.tox
.tox installdeps: tox-wheel >= 1.0.0, tox >= 3.7.0
WARNING: test command found but not installed in testenv
  cmd: /usr/local/pyenv/shims/python
  env: /disk1/workspace/CI-someorg-somerepo/somerepo/.tox/.tox
Maybe you forgot to specify a dependency? See also the allowlist_externals envconfig setting.

DEPRECATION WARNING: this will be an error in tox 4 and above!
```
Looks like this line should use the full path to the venv:
https://github.com/ionelmc/tox-wheel/blob/c802827e988a95f28f258bda6ca585f234f8fdaa/src/tox_wheel/plugin.py#L169

**Comment by ionelmc** [comment]
Can you paste your tox.ini and full logs? It's not clean what's going on over there...

**Comment by tucked** [comment]
This actually appears to be due to a race between 2 instances of  `tox` working on the same directory simultaneously (our CI bind-mounts the same dir into 2 containers). `tox-pyenv` is also in play, and when I run serially, everything passes.

Apologies for the false alarm!

**Comment by tucked** [comment]
Related: https://github.com/tox-dev/tox/issues/2515
